[client]
toolbarMode = "viewer" # Ukrywa opcje developerskie dla użytkownika

[theme]
base = "dark" # Wymusza ciemny motyw
primaryColor = "#00ccff" # Możesz tu ustawić swój niebieski kolor wiodący

[server]
headless = true
port = 8501
address = "192.168.2.153" # Pozwala na dostęp z innych komputerów w sieci lokalnej